theme = "dracula"

[editor]
scrolloff = 10
mouse = true
shell = ["zsh", "-c"]
line-number = "relative"
cursorline = true
cursorcolumn = true
auto-format = false
bufferline = "always"
color-modes = true
default-line-ending = "lf"
insert-final-newline = true
rulers = [80]
completion-replace = true
true-color = true
undercurl = true
end-of-line-diagnostics = "hint"
popup-border = "all"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode", "file-name", "version-control"]
center = []
right = [
  "spinner",
  "workspace-diagnostics",
  "diagnostics",
  "file-type",
  "position",
  "position-percentage",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.lsp]
display-inlay-hints = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[keys.insert]
j = { f = "normal_mode" }
f = { j = "normal_mode" }
